run_name: 'arc_filling_cond'
logdir: './logs/'
resume: True
wandb_params:
  mode: 'online' #'online'  # disabled, offline, online
  # entity: 'test_entity'
  tags: 'mac'
  # resume: 'must'
  run_id: 'u1jniql5'
dataset: 'arc_filling'
datadir: './data/arc/'
enable_progress_bar: True
num_sanity_val_steps: 0

mode: 'pocket_conditioning'
pocket_representation: 'full-atom'
batch_size: 8
lr: 1.0e-4
n_epochs: 1000
num_workers: 2
acc: 'gpu'
clip_grad: True
augment_rotation: False
augment_noise: 0

auxiliary_loss: False
loss_params:
  max_weight: 1.0
  schedule: 'linear'
  clamp_lj: 3.0

egnn_params:
  # device: 'gpu'
  edge_cutoff: 7.0
  joint_nf: 16
  hidden_nf: 16
  n_layers: 2
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 10
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 4]  # [x, h]

eval_epochs: 25000
visualize_sample_epoch: 1
visualize_chain_epoch: 1
eval_params:
  n_eval_samples: 100
  eval_batch_size: 1
  smiles_file: './data/arc/'
  n_visualize_samples: 2
  keep_frames: 10