run_name: 'arc_small'
logdir: './logs/'
resume: False
wandb_params:
  mode: 'disabled' #'online'  # disabled, offline, online
  tags: 'mac'
  run_id:
dataset: 'arc_small'
datadir: './data/arc/small'
enable_progress_bar: True
num_sanity_val_steps: 0

mode: 'pocket_conditioning'
pocket_representation: 'full-atom'
batch_size: 32
lr: 1.0e-4
n_epochs: 10
num_workers: 4
acc: 'cpu'
clip_grad: True
augment_rotation: False
augment_noise: 0

auxiliary_loss: False
loss_params:
  max_weight: 1.0
  schedule: 'linear'
  clamp_lj: 3.0

egnn_params:
  # device: 'gpu'
  edge_cutoff: 7.0
  joint_nf: 8
  hidden_nf: 8
  n_layers: 1
  attention: False
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: True
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 10
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 4]  # [x, h]
  noise_x: False

eval_epochs: 1
visualize_sample_epoch: 1
visualize_chain_epoch: 1
eval_params:
  eval_batch_size: 1
  n_visualize_samples: 2